[[OpenEXR]]
arch = "aarch64"
git-tree-sha1 = "6c719f921a9f107cca8eb614c4cec6e6a2cc93e7"
os = "macos"

    [[OpenEXR.download]]
    sha256 = "f410f0b8f08b3abc7be0da92c3ba05473302acf50cd48db4bd78b658b8aac9cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.aarch64-apple-darwin.tar.gz"
[[OpenEXR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a109fc8244a15b17267651e75ceb9dbeb7a5f37"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "be405227b1c585ae91b6263d8f808a85c5e319ca5b65a59943c05fc6949ab03a"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72b2f7759f750fb894dededc912f6a124a1ef8aa"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "29df6ba26dc3cac683e761d224cfbf5f051ade452b0c83b7959b6766a8a01cf0"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.aarch64-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "aarch64"
git-tree-sha1 = "87dd5e8735c3ba8c909c1fbd5438ee88040a2afb"
os = "freebsd"

    [[OpenEXR.download]]
    sha256 = "2dc8e7a5a0260fe97bb75186f9724378d396dbba59c8022d4278c980bdd285af"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.aarch64-unknown-freebsd.tar.gz"
[[OpenEXR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3577e20ecda085a7c702b0893d378009095c8639"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "20519b4ee60768afce7eb7945bf351caf7a0535ac99d240c7ecdc8182848e018"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a0a0efea607b3371183e0b49fbe5f1ea6ea0ed6"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "14942b94c6e5abf8215c1ae67d85cc55a1c5485ddcf91889db77cef9269448ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.armv6l-linux-musleabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e045f3900c84fc860aaa6cd9ebbbe355a3945b6"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "c00f0effd29c1eaae462dee237ab7ba9a28ad62f1062b76b97069c2392616484"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8cb920633278c33c1733a13b234dabc7da2c6df"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "3175a2b231dc58c98ad82e63660c684fa664f319c18ee5f49d0f89a5235232e9"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd55eff2423b04cc2cfa9c2f15278c099991e9da"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "63ed9f491af22da7dd4248d280f39fca8348c3d38fc51ce8ceae0d38aaee12a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.i686-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c92ee7ba92f8ec109c5769f9c3cce0cf68971949"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "af40d3e68715a9c88d01efeecaba94d9fd3ff72b029ba24b6818ade3cb0122c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.i686-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "458f2cddc890e702d90363730b7b57f9c67c8fd6"
os = "windows"

    [[OpenEXR.download]]
    sha256 = "7ae99b5082587ff80c9efb7c8fb836f9e1f9143d37314411d34a56e897bd6066"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.i686-w64-mingw32-cxx11.tar.gz"
[[OpenEXR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a4933289930c884a8e71d8db3875d8be926d905"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "c98587ac058802cdac40629c8382ea4eda853c35efe119f634d3f9bccf62d5fa"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c12f981514784d961805f52d2deca75aed853885"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "ae0befb376e6728c86321cc6c2b0836f310249e637402e2b265ac43d1a64fd75"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
git-tree-sha1 = "58c2578e9f389f04e72fe093c871bee6d7922d57"
os = "macos"

    [[OpenEXR.download]]
    sha256 = "91cfea487792a20d5c93fdd14759e90dbe3e0cdb2c324c50377094b7f16be884"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.x86_64-apple-darwin.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f68f5500f9af364d81668c94044681429747434"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "f1e9c121f96f4a58f410e0d5e2ba082c47ca8df934523cc51ca43eceb86ab73e"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0682001774b2e25d6041cd5339de47ab397d25d"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "fedaf78ee45cdd056b6b729f7c28f8bf87842b3f3c56363bd56dd961f7c35045"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.x86_64-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
git-tree-sha1 = "a092df4adee22a508ec31437ac81a384ef7ead39"
os = "freebsd"

    [[OpenEXR.download]]
    sha256 = "8eb2be142447fbbcf22aee76b06963b1e83f47bece9ab5bb10b4681a542083ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.x86_64-unknown-freebsd.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84df29e1dd87ff06098555626290b74bcc4df0e7"
os = "windows"

    [[OpenEXR.download]]
    sha256 = "169aba80ca487ec314098e6977a527cbe5f7c36d702f96184816ce515db6c7d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.14+0/OpenEXR.v3.4.14.x86_64-w64-mingw32-cxx11.tar.gz"
