[[OpenEXR]]
arch = "aarch64"
git-tree-sha1 = "d81bc8dd3de108ca30f7cb237be87fce7a05ab3b"
os = "macos"

    [[OpenEXR.download]]
    sha256 = "0acdc9de1eff26aa3bfacc283348e7f555163c0c799630bb4b209ebdaa1189a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.aarch64-apple-darwin.tar.gz"
[[OpenEXR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b63cd07f38b0819fa990d431672105c151e610c9"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "be72b5ed3d5632d440c1d6342ea6bc9148c725106490a1ce96fd32957ce1ddbd"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "456d03bbb30d4c57aec38f21be876c6de5e61da8"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "5d42d08792d5c955a436d42539d1f4e704137a38c66bcffeb7b0e2b9df7dd59a"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.aarch64-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "aarch64"
git-tree-sha1 = "cba2bda237977273ee874c33603a3f1eab4b5ab8"
os = "freebsd"

    [[OpenEXR.download]]
    sha256 = "b545ae26877405ee228d5ffe393b4533bb1a311bfcc2f05b127e307c1b5e00db"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.aarch64-unknown-freebsd.tar.gz"
[[OpenEXR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9401efbd6c19799f1df336c4bbea9208b6cc1ad5"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "bd77aee1a7ebc18875ffecbdd94fd6fdad48089c824f7a83680286a6ecd276f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86215cd5f2a4e46628b201787abaf041c94d7849"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "f760bfd5e5c3fb8ae3cf5bf769816f409d5869f4fb837d65b25aff119d00a4f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "810c0df67aa92b58bd5128872dd648c81b21f3dd"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "7d0edf1bb462f85177cb788f52acbc66448cf5610b809880b5cfe9d09718bc8c"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c195594717cb61de94ad373300b4fa18e2e5b21"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "9b93cf930be3c097d489e6cd2b04c92cb9e0ce6b41de33a659b2c48c2c62d60f"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "682f4bd41e0d30f9f56278e87f3c2afcd0beebe3"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "0002f8d090711d6dbc339305257f84a8963afcc33d4ae1d7e4276ec15b9fc922"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.i686-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c94fba02338c7dfdb425fa6e3d98968215057b2"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "51b2f51692a4b73a5668019df249d6f496f2caccc198aa90d597c98f444d4cd3"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.i686-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26899a8a91183befc086169ecc1e5acb091a8dce"
os = "windows"

    [[OpenEXR.download]]
    sha256 = "91e4747710ac60be4535a09ba304e1f31ee7eccb726a4a06452b989261c13633"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.i686-w64-mingw32-cxx11.tar.gz"
[[OpenEXR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a60ab26ba8608782367a7f50a03aca0b602786f"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "035fb7427e79d86489409b05e088b0ce5c9e175d00b0d7e3b63318486f5247cb"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98d73f72b10e8fb207c78295bd4121d884625d1a"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "f7c1e93c6d9e32a6d3735aeb1b359b462f95de1002239f39b7bafdc2912dff60"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
git-tree-sha1 = "dc6b49d21350671145c4c80f14b8c611617450c0"
os = "macos"

    [[OpenEXR.download]]
    sha256 = "43e43501437262d74b1774df56d918d96fc3b5be5363cd30015e8fed6be52d9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.x86_64-apple-darwin.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe056d90329ab23c957e2d2421ea58aa39422b9e"
libc = "glibc"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "dff48695e21e5e93a57c8b97d7a441f0c412daa9519aab3ceb02951602b744bb"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a95f42d29b09d8c95609d2388a34bca113c95879"
libc = "musl"
os = "linux"

    [[OpenEXR.download]]
    sha256 = "779535c0882309778bdd39e00533315769cfb8140b1715f8157ed46cde667239"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.x86_64-linux-musl-cxx11.tar.gz"
[[OpenEXR]]
arch = "x86_64"
git-tree-sha1 = "4e1a5173aef7c1991b5bd4a66f20ecc167f77f71"
os = "freebsd"

    [[OpenEXR.download]]
    sha256 = "657c3a1b53b976ca366f972acb804fc259603a9346f3a494a4820b4c40faf3f6"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.x86_64-unknown-freebsd.tar.gz"
[[OpenEXR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16b1a8271fa8292da8b9fbfd2e4fce599ca3e9c8"
os = "windows"

    [[OpenEXR.download]]
    sha256 = "1aea94b4e405297d722c39622d057293a54e2832b182484ebcb46a47b5463a16"
    url = "https://github.com/JuliaBinaryWrappers/OpenEXR_jll.jl/releases/download/OpenEXR-v3.4.8+0/OpenEXR.v3.4.8.x86_64-w64-mingw32-cxx11.tar.gz"
