# Autogenerated wrapper script for OpenEXR_jll for x86_64-apple-darwin
export libIex, libIlmThread, libOpenEXR, libOpenEXRUtil

using Imath_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("OpenEXR")
JLLWrappers.@declare_library_product(libIex, "@rpath/libIex-3_0.27.dylib")
JLLWrappers.@declare_library_product(libIlmThread, "@rpath/libIlmThread-3_0.27.dylib")
JLLWrappers.@declare_library_product(libOpenEXR, "@rpath/libOpenEXR-3_0.27.dylib")
JLLWrappers.@declare_library_product(libOpenEXRUtil, "@rpath/libOpenEXRUtil-3_0.27.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Imath_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libIex,
        "lib/libIex-3_0.27.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libIlmThread,
        "lib/libIlmThread-3_0.27.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOpenEXR,
        "lib/libOpenEXR-3_0.27.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOpenEXRUtil,
        "lib/libOpenEXRUtil-3_0.27.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
